### ISSUE TITLE
Addition can cause RuntimeException: no fields

### ISSUE THREAD

**Issue by mplamann** [wyvernlang/wyvern#162]
The following code generates an error when run:

    import wyvern.option
    val obj = new
      def length():Int = 3
    val x = option.Some(obj)
    x.getOrElse(() => obj).length() + 1

results in the error

    Exception in thread "main" java.lang.RuntimeException: no fields
      at wyvern.target.corewyvernIL.expression.IntegerLiteral.getField(IntegerLiteral.java:108)
      at wyvern.target.corewyvernIL.expression.FieldGet.interpret(FieldGet.java:70)
      at wyvern.target.corewyvernIL.expression.Let.interpret(Let.java:84)
      at wyvern.target.corewyvernIL.expression.Let.interpret(Let.java:84)
      at wyvern.target.corewyvernIL.expression.Let.interpret(Let.java:84)
      at wyvern.target.corewyvernIL.expression.Let.interpret(Let.java:84)
      at wyvern.tools.Interpreter.main(Interpreter.java:70)

It seems like the `+ 1` is parsing improperly, generating a FieldGet instead of an Invocation.
Rearranging the addition to look like

    import wyvern.option
    val obj = new
      def length():Int = 3
    val x = option.Some(obj)
    1 + x.getOrElse(() => obj).length()

Runs without error.

**Comment by potanin** [comment]
This bug is still present in exactly the above form in the latest wyvern btw.

**Comment by JonathanAldrich** [comment]
this works in the current system (not sure when the fix was pushed)
