### ISSUE TITLE
ClassCastException when trying to match on datatagged Option[T]

### ISSUE THREAD

**Issue by hcnelson99** [wyvernlang/wyvern#230]
Test case:
```
type Option comprises Some, None
    type T
    val isDefined:Boolean

type Some extends Option
    type T
    val value: this.T
    val isDefined:Boolean
	
def Some[T](x:T):Some[T] = new
    type T = T
    val value:T = x
    val isDefined:Boolean = true

type None extends Option
    type T
    val isDefined:Boolean

def None[T]():None[T] = new
    type T = T
    val isDefined:Boolean = false

val x : Option[Int] = Some[Int](42)

match x:
    s: Some[Int] => s.value
    n: None[Int] => 0
```

Observed behavior:
```
Exception in thread "main" java.lang.ClassCastException: wyvern.target.corewyvernIL.type.RefinementType cannot be cast to wyvern.target.corewyvernIL.type.NominalType
	at wyvern.tools.typedAST.core.expressions.Case.generateILCase(Case.java:106)
	at wyvern.tools.typedAST.core.expressions.Match.lambda$generateIL$0(Match.java:113)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at wyvern.tools.typedAST.core.expressions.Match.generateIL(Match.java:114)
	at wyvern.tools.typedAST.core.expressions.Match.generateIL(Match.java:28)
	at wyvern.tools.typedAST.interfaces.ExpressionAST.genTopLevel(ExpressionAST.java:28)
	at wyvern.tools.typedAST.core.Sequence.genTopLevel(Sequence.java:288)
	at wyvern.tools.typedAST.core.Script.generateIL(Script.java:49)
	at wyvern.target.corewyvernIL.support.ModuleResolver.load(ModuleResolver.java:238)
	at wyvern.tools.Interpreter.main(Interpreter.java:61)
```

Expected behavior: Clean execution

**Comment by JonathanAldrich** [comment]
Obviously there should be no class cast exception.  That's easy to fix, but getting it to work correctly is a bit more subtle because we have to keep the knowledge of the parameter [Int] around in the match, and combine it with the information gained by the match.

**Comment by JonathanAldrich** [comment]
Matching on parameterized types now works, but you have to not include the type parameter in the match.  This was simpler to implement, and has the advantage that you can't get the parameter wrong.  For example, the following code returns 15 as expected:

```
tagged type Option comprises Some, None
    type T
    val isDefined:Boolean
    
tagged type Some extends Option
    type T
    val value: this.T
    val isDefined:Boolean
    
tagged type None extends Option
    type T
    val isDefined:Boolean

def testIt(x:Option[Int]):Int = match x:
    s: Some => s.value
    n: None => 0

val s1:Some[Int] = new
    type T=Int
    val isDefined = true
    val value = 15
    
testIt(s1)

```
I'll see if I can support type parameters in the match statement (checking them for correctness) at some point in the future.

**Comment by hcnelson99** [comment]
Related bug. This is not a blocking issue. In fact, I might come back and try to fix this one. It has a very easy workaround.

Test case:
```
import wyvern.option

datatype Foo
    X
    Y

val f: Foo = X()

val a = match f:
    x: X => option.None[String]()
    y: Y => option.None[String]()
```
Expected behavior: Clean run
Observed behavior:
```
Exception in thread "main" java.lang.ClassCastException: wyvern.target.corewyvernIL.type.RefinementType cannot be cast to wyvern.target.corewyvernIL.type.NominalType
	at wyvern.tools.typedAST.core.expressions.Match.lambda$generateIL$0(Match.java:120)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at wyvern.tools.typedAST.core.expressions.Match.generateIL(Match.java:121)
	at wyvern.tools.typedAST.core.expressions.Match.generateIL(Match.java:29)
	at wyvern.tools.typedAST.core.declarations.ValDeclaration.genTopLevel(ValDeclaration.java:70)
	at wyvern.tools.typedAST.core.Sequence.genTopLevel(Sequence.java:285)
	at wyvern.tools.typedAST.core.Script.generateTLC(Script.java:48)
	at wyvern.tools.typedAST.core.Script.generateIL(Script.java:58)
	at wyvern.target.corewyvernIL.support.ModuleResolver.load(ModuleResolver.java:271)
	at wyvern.tools.Interpreter.main(Interpreter.java:61)
```

Workaround: Specify nominal expectedType
```
import wyvern.option

datatype Foo
    X
    Y

val f: Foo = X()

val a: option.Option = match f:
    x: X => option.None[String]()
    y: Y => option.None[String]()
```

**Comment by JonathanAldrich** [comment]
Fixed so the first example works (by ignoring the type annotation, with a warning message).
