### ISSUE TITLE
Runtime ClassCastException with ValDeclType

### ISSUE THREAD

**Issue by potanin** [wyvernlang/wyvern#298]
Unfortunately, GitHub does not support attaching source files. So here is a source file to reproduce this bug (note this issue maybe related to #230).

binarytree.wyv
===========

require stdout

import wyvern.option

type Option = option.Option

resource type BinaryTree
  var left:Option[BinaryTree]
  var right:Option[BinaryTree]
  def print():Unit

var tree:BinaryTree = new
  var left:Option[BinaryTree] = option.None[BinaryTree]()
  var right:Option[BinaryTree] = option.None[BinaryTree]()
  def print():Unit
    if(this.left.isDefined() && this.right.isDefined())
        stdout.print("Both defined!\n")
      else
        if(this.left.isDefined())
            stdout.print("Only left!\n")
          else
            if(this.right.isDefined())
                stdout.print("Only right!\n")
              else
                stdout.print("Empty!\n")

tree.print()

==========

When running the above with wyvern binarytree.wyv command one gets:

lap7:Wyvern alex$ wyvern binarytree.wyv 
Exception in thread "main" java.lang.ClassCastException: wyvern.target.corewyvernIL.decltype.ValDeclType cannot be cast to wyvern.target.corewyvernIL.decltype.DefDeclType
	at wyvern.target.corewyvernIL.expression.MethodCall.methodDeclarationNotFoundMsg(MethodCall.java:426)
	at wyvern.target.corewyvernIL.expression.MethodCall.typeMethodDeclaration(MethodCall.java:395)
	at wyvern.target.corewyvernIL.expression.MethodCall.typeCheck(MethodCall.java:140)
	at wyvern.target.corewyvernIL.support.InvocationExprGenerator.<init>(InvocationExprGenerator.java:30)
	at wyvern.tools.typedAST.core.expressions.Invocation.getCallableExpr(Invocation.java:96)
	at wyvern.tools.typedAST.core.expressions.Invocation.generateIL(Invocation.java:65)
	at wyvern.tools.typedAST.core.expressions.Application.generateILForTuples(Application.java:184)
	at wyvern.tools.typedAST.core.expressions.Application.generateIL(Application.java:121)
	at wyvern.tools.typedAST.core.declarations.DefDeclaration.generateDecl(DefDeclaration.java:194)
	at wyvern.tools.typedAST.core.expressions.New.generateIL(New.java:135)
	at wyvern.tools.typedAST.core.expressions.New.generateIL(New.java:26)
	at wyvern.tools.typedAST.core.declarations.VarDeclaration.generateDecl(VarDeclaration.java:76)
	at wyvern.tools.typedAST.core.expressions.New.generateIL(New.java:135)
	at wyvern.tools.typedAST.core.expressions.New.generateIL(New.java:26)
	at wyvern.tools.typedAST.core.declarations.ValDeclaration.getILValueType(ValDeclaration.java:102)
	at wyvern.tools.typedAST.core.declarations.ValDeclaration.genTopLevel(ValDeclaration.java:67)
	at wyvern.tools.typedAST.core.declarations.VarDeclaration.genTopLevel(VarDeclaration.java:114)
	at wyvern.tools.typedAST.core.Sequence.genTopLevel(Sequence.java:274)
	at wyvern.tools.typedAST.core.Script.generateTLC(Script.java:48)
	at wyvern.tools.typedAST.core.Script.generateIL(Script.java:58)
	at wyvern.target.corewyvernIL.support.ModuleResolver.loadContinuation(ModuleResolver.java:294)
	at wyvern.target.corewyvernIL.support.ModuleResolver.load(ModuleResolver.java:374)
	at wyvern.target.corewyvernIL.support.ModuleResolver.load(ModuleResolver.java:358)
	at wyvern.tools.Interpreter.main(Interpreter.java:61)

**Comment by potanin** [comment]
It has to do with the this.left.isDefined resolving from the Option type. So can simplify the print method to just:

  def print():Unit
    if (this.left.isDefined())
      stdout.print("Blah")

**Comment by potanin** [comment]
So the issue is actually quite simple. Imagine one has a member "val" instead of "def" (like stdlib Option does where isDefined is a val. You then call it as if though it was a "def": blah.isDefined() instead of blah.isDefined. This indeed causes a correct error, BUT MethodCall.java on line 426 has an assumption that it has to be DefDeclType (not ValDeclType) and so the cast fails! It appears that either a proper error needs to be reported with "val" being used where "def" is expected or MethodCall.java needs to be made to handle this case. Any suggestions? Should be trivial to fix to avoid Java error and replace it with Wyvern error.
