### ISSUE TITLE
Crash on var assignment of parameter with the same name

### ISSUE THREAD

**Issue by potanin** [wyvernlang/wyvern#313]
The following throws a RuntimeException (possibly due to scoping of `var`/`val`'s).

I attached a txt file because silly GitHub does not allow attaching source files like .wyv or wyt - is there a setting we can fix?

[bug.wyv.txt](https://github.com/wyvernlang/wyvern/files/2990494/bug.wyv.txt)

```
type Pair
  type T
  def first():this.T

def makeIntPair(first:Int):Pair[Int] = new
  var first:Int = first
  def first():this.T = this.first
```

```
taniwha:1 Immutability alex$ wyvern bug.wyv 
Exception in thread "main" java.lang.RuntimeException: Ambiguous findDecl: first
	at wyvern.target.corewyvernIL.type.StructuralType.findDecl(StructuralType.java:260)
	at wyvern.target.corewyvernIL.expression.FieldGet.typeCheck(FieldGet.java:67)
	at wyvern.target.corewyvernIL.decl.DefDeclaration.typeCheck(DefDeclaration.java:123)
	at wyvern.target.corewyvernIL.expression.New.typeCheck(New.java:138)
	at wyvern.target.corewyvernIL.decl.DefDeclaration.typeCheck(DefDeclaration.java:123)
	at wyvern.tools.typedAST.core.declarations.DeclSequence.genTopLevel(DeclSequence.java:194)
	at wyvern.tools.typedAST.core.Sequence.genTopLevel(Sequence.java:288)
	at wyvern.tools.typedAST.core.Script.generateTLC(Script.java:48)
	at wyvern.tools.typedAST.core.Script.generateIL(Script.java:58)
	at wyvern.target.corewyvernIL.support.ModuleResolver.loadContinuation(ModuleResolver.java:295)
	at wyvern.target.corewyvernIL.support.ModuleResolver.load(ModuleResolver.java:394)
	at wyvern.target.corewyvernIL.support.ModuleResolver.load(ModuleResolver.java:378)
	at wyvern.tools.Interpreter.main(Interpreter.java:61)
taniwha:1 Immutability alex$ wyvern bug.wyv 
Exception in thread "main" java.lang.RuntimeException: Ambiguous findDecl: first
	at wyvern.target.corewyvernIL.type.StructuralType.findDecl(StructuralType.java:260)
	at wyvern.target.corewyvernIL.expression.FieldGet.typeCheck(FieldGet.java:67)
	at wyvern.target.corewyvernIL.decl.DefDeclaration.typeCheck(DefDeclaration.java:123)
	at wyvern.target.corewyvernIL.expression.New.typeCheck(New.java:138)
	at wyvern.target.corewyvernIL.decl.DefDeclaration.typeCheck(DefDeclaration.java:123)
	at wyvern.tools.typedAST.core.declarations.DeclSequence.genTopLevel(DeclSequence.java:194)
	at wyvern.tools.typedAST.core.Sequence.genTopLevel(Sequence.java:288)
	at wyvern.tools.typedAST.core.Script.generateTLC(Script.java:48)
	at wyvern.tools.typedAST.core.Script.generateIL(Script.java:58)
	at wyvern.target.corewyvernIL.support.ModuleResolver.loadContinuation(ModuleResolver.java:295)
	at wyvern.target.corewyvernIL.support.ModuleResolver.load(ModuleResolver.java:394)
	at wyvern.target.corewyvernIL.support.ModuleResolver.load(ModuleResolver.java:378)
	at wyvern.tools.Interpreter.main(Interpreter.java:61)`
```

**Comment by potanin** [comment]
Actually it is worse and the following what I thought was correct code fails too:

```
type Pair
  type T
  def first():this.T
  def second():this.T

def makeIntPair(f:Int, s:Int):Pair[Int] = new
  type T = Int
  var first:Int = f
  var second:Int = s
  def first():this.T = this.first
  def second():this.T = this.second
  def print():Unit
    stdout.print("First: ")
    stdout.printInt(this.first)
    stdout.println()
    stdout.print("Second: ")
    stdout.printInt(this.second)
    stdout.println()

var pair1:Pair[Int] = makeIntPair(3, 2)
var pair2:Pair[Int] = makeIntPair(4, 5)

pair1.print()
pair2.print()
```

**Comment by JonathanAldrich** [comment]
You can't name a var or val field the same as a method.

But of course the typechecker should give a good error message rather than
an exception--thanks for reporting this.
